export type SuccessLevel = 'success' | 'partial' | 'paused' | 'not-started'

export type WorkJourney = {
  success: SuccessLevel
  successLabel: string
  background: string
  impact: string
  process: string[]
  myWork: string[]
  challenges: string[]
  communication: string[]
  rework: string[]
  decision: string
  limitation: string
  learning: string
  finalResult: string
}

export const workJourneys: Record<string, WorkJourney> = {
  'localstack-1057': {
    success: 'success',
    successLabel: '成功合并并完成完整验证',
    background: 'Dataverse Frontend 的本地开发环境和来自 fork 的 GitHub Actions 需要 IQSS 私有 AWS S3 credentials。外部贡献者拿不到 secrets，因此文件上传和六组 S3 相关 E2E 会失败；把真实 credentials 暴露给不受信任的 fork 又会形成安全风险。',
    impact: '外部贡献者无法在本地或 fork CI 验证文件工作流，维护者必须依赖私有凭证；若把真实 keys 交给不受信任的 fork，又会形成直接的 secrets exposure 风险。',
    process: ['先证明失败来自测试基础设施，而不是 Dataverse 上传业务逻辑。', '比较继续使用 AWS、跳过测试和使用本地 S3-compatible 服务三种路线，选择 LocalStack。', '统一标准开发环境、Shibboleth 环境和 fork CI 的 storage topology。', '解决容器与浏览器共享 hostname、presigned URL、path-style access、multipart CORS 和 ETag。', '用 healthcheck、completion marker、stale-marker cleanup 和故障注入证明初始化状态可信。'],
    myWork: ['新增并配置 LocalStack S3 服务和 bucket 初始化脚本。', '从示例配置和 GitHub Actions 中删除真实 S3 keys。', '配置浏览器 CORS、暴露 ETag，并验证 single-part 与 multipart 上传。', '编写开发文档并完成标准与 Shibboleth 两套 Compose 验证。', '根据 review 修改 readiness 逻辑并推动完整 CI 重跑。'],
    challenges: ['浏览器消费的 presigned URL 必须同时能从宿主机和容器网络访问。', 'bucket 存在不代表 CORS 已配置完成，原始 healthcheck 可能产生 false healthy。', 'LocalStack Community 的持久化能力不足，不能仅靠 volume mount 做出错误承诺。', 'fork workflow 没有 repository secrets，所有验证必须真正 credential-free。'],
    communication: ['Philip 先分享 #1053，随后把 #1056 合并到同一个交付目标。', 'Philip 删除自己机器上的 S3 keys 后实际上传成功，并公开批准 PR。', 'Philip 询问是否可以把 LocalStack 数据放进 docker-dev-volumes；我实测并解释 Community 版本需要额外 backup/restore，建议当前 PR 保持 ephemeral、持久化另开后续 issue。', 'Cheng 指出 healthcheck 只检查 bucket、不检查 CORS；我接受建议并请他重跑我无权限重跑的 E2E。'],
    rework: ['在两个 Compose 文件中加入 completion marker 检查并扩大冷启动重试预算。', '初始化开始时清理旧 marker，只有 CORS 成功后才重新写入。', '注入初始化失败，确认容器不会错误报告 healthy。', '重新运行完整 fork PR workflow：146 E2E、267 component tests。'],
    decision: '选择 credential-free LocalStack 作为三套环境的共同 S3 topology；拒绝向 fork 暴露 AWS secrets、跳过 S3 tests，以及在 Community 版本上承诺未经证明的 persistence。',
    limitation: '本次交付刻意不解决 LocalStack Community 的持久化；7 个 pending E2E 是既有状态，不属于本次修复。',
    learning: '环境 readiness 必须由使用者真正依赖的结果定义。容器启动或 bucket 存在都不够，只有 CORS、presigned URL 和失败恢复一起成立才算 ready。',
    finalResult: 'PR #1057 获 Philip 和 Cheng 批准并合并。E2E 146 项中 139 passing、7 个原有 pending、0 failing；267 个 component tests 全部通过。贡献者不再需要 IQSS AWS credentials。',
  },
  'guestbook-12220': {
    success: 'success',
    successLabel: '本人 QA 与修复成功；父 PR 仍开放',
    background: 'PR #12220 的目标是修复 Guestbook Cancel 按钮，但分支同时把 Terms of Access 的显示条件从 termsOfAccess 改成 disclaimer，并引用不存在的 bundle key。与此同时 JSF CI 出现失败，容易让人把真实 regression 和无关测试噪声混为一谈。',
    impact: '受限文件用户可能看不到必要的 Terms of Access，同时无关 JSF 失败会干扰 merge 判断，让真实 regression 被错误归因或遗漏。',
    process: ['把 PR diff 与 develop 逐行比较，先隔离 Cancel 变更和无关改动。', '识别 Terms 显示条件与 bundle key 两个 regression。', '检查失败 trace、fixture、请求和 JSF/EL 输出，判断失败测试是否真正经过 Terms path。', '建立 controlled before/after 页面，证明 Terms 内容在修复前消失、修复后恢复。', '用独立两行 PR 提供可合并修复；父分支吸收后关闭为 superseded。'],
    myWork: ['提交两次准确的 inline review finding。', '创建 PR #12608，只修改两行生产代码。', '运行完整 JSF suite 和 Chromium、Firefox、WebKit 验证。', '制作带 QA-TOA-SENTINEL-12220 的前后对比截图。', '明确说明父 PR 的 Cancel 功能归原作者所有，只声明自己的 QA 与 Terms 修复。'],
    challenges: ['不能因为 CI 失败就撤销正确修复，也不能因为 Cancel 主路径工作就忽略 diff 中的 regression。', '需要证明失败 fixture 没有 Terms、disclaimer、guestbook 或 restricted file，而不是凭直觉说“无关”。', '修复被父 PR 吸收后，必须关闭自己的 PR 并保留可追溯证据。'],
    communication: ['Philip 直接分配 QA，并帮助触发 preview image。', '我提交 #12608 后，Philip 表示尚未理解问题并要求 screenshot。', '我没有继续写长解释，而是提供 controlled before/after 截图，展示 Terms 行和 sentinel 文本如何恢复。', 'Philip 随后询问原作者是否要把 #12608 合入 #12220；Steven 将同样修改直接吸收。'],
    rework: ['在 Philip 说“不够清楚”后，把抽象代码说明重做成视觉证据。', '在父分支吸收修复后重新检查官方 CI：JSF 43/43、三个浏览器、integration 和 CodeQL。', '确认 #12608 已失去独立合并必要性并关闭，避免重复交付。'],
    decision: '把 Cancel 主功能 QA 与隐藏的 Terms regression 拆开处理；用独立两行修复提供清晰证据，父 PR 吸收同一修改后关闭为 superseded，避免重复交付。',
    limitation: '父 PR #12220 仍由原作者负责；本人只声明独立 QA、regression finding 和修复证据完成。',
    learning: 'CI 红灯不能替代因果分析。先证明失败测试是否经过可疑代码路径，再用 controlled before/after 证据消除沟通歧义。',
    finalResult: 'Terms regression 被父 PR commit bf019c4 吸收，完整 JSF 两次 43/43 通过。本人 QA 和修复成功；父 PR #12220 仍由原作者处理，未被错误宣称为本人完成。',
  },
  'map-337': {
    success: 'success',
    successLabel: '当天修复、合并并部署生产',
    background: 'Dataverse 官网 installations map 出现 “API KEY REQUIRED” 水印。Tile request 返回 HTTP 200，但实际 PNG 内容是错误图，直接影响公开生产页面的可信度和视觉质量。',
    impact: '面向公众的 installations map 持续展示错误水印，直接降低 Dataverse 官网可信度，也让 150 个机构点位的公开展示失去可用底图。',
    process: ['从浏览器网络请求和实际 PNG 内容确认问题边界。', '排除 Leaflet、CORS、JavaScript 和 150 条坐标数据。', '比较 OSM Standard、OpenTopoMap、带 key 的 CARTO 和 OpenFreeMap。', '按照最小风险、无需 key、attribution 和政策要求给出候选。', '实施 Philip 选择的 OSM Standard，并执行本地、GitHub Pages 和生产验证。'],
    myWork: ['复现生产水印并保存候选截图。', '验证全部 150 个 installation markers。', '修改 tile endpoint、移除 CARTO subdomains、更新 attribution。', '检查 popup、zoom、pan、移动端宽度和请求清单。', '提交 PR #338 并在生产部署后再次检查。'],
    challenges: ['HTTP 200 容易制造“服务正常”的假象，必须检查响应内容。', '替代 provider 不只是技术选择，还受 key、usage policy 和 attribution 约束。', '需要把技术比较缩成 Philip 可以快速做决定的小块信息。'],
    communication: ['Philip 明确提出任务，要求本地 screenshot 和多个候选方案。', '我把候选按视觉结果、key 要求、实施成本和 attribution 分开呈现。', 'Philip 选择 OSM Standard，并在自己的机器上确认没有水印后批准。', '合并后 Philip 主动通知 dataverse.org 已上线且显示正常。'],
    rework: ['根据 Philip 的选择，从比较阶段收敛为单一 OSM 最小改动。', '在本地通过后重新做 760px viewport 和零 CARTO request 检查。', '上线后再跑一次生产 smoke verification，而不是把 merge 当作完成。'],
    decision: '在比较 key、政策、attribution、实施成本和视觉结果后，按 Philip 的选择采用 OSM Standard，并保持改动只限 tile endpoint 与 attribution。',
    limitation: '修复移除了 CARTO 故障，但公开地图仍依赖外部 tile service 及其 usage policy；没有重构 Leaflet 或数据层。',
    learning: 'HTTP 200 只代表请求成功，不代表内容正确。生产问题需要检查 payload，并在部署后再次验证真实页面。',
    finalResult: 'PR #338 当天 Approved、merged、deployed。150 个 markers、交互、attribution 和移动端均通过，CARTO requests 为 0，生产水印消失。',
  },
  'password-12544': {
    success: 'success',
    successLabel: 'QA 成功并记录配置风险；PR 已合并',
    background: 'PR #12544 把 password-reset 的硬编码英文迁移到 resource bundles。默认配置看起来正常，但使用 dataverse.lang.directory 的安装可能继续加载尚未包含新 key 的外部语言包。',
    impact: '默认安装看似正常，但使用外部 language directory 的机构可能在升级后遇到空翻译、事务 rollback 或 generic password-reset error。',
    process: ['先在 Dataverse 6.11 建立行为 baseline。', '启动 EN/FR demo 与 Maildev，使用 PR preview image 执行完整 password-reset。', '验证翻译加入后 French completion email 是否真正送达。', '沿 BundleUtil 和 dataverse.lang.directory 路径分析 external pack 缺 key 的行为。', '把“默认路径通过”和“特殊部署有 residual risk”分开报告。'],
    myWork: ['搭建 EN/FR 测试环境和邮件捕获环境。', '执行从 reset request 到 completion notification 的完整用户流程。', '验证法语邮件正文，而不是只检查代码中的 bundle key。', '定位 null translation 可能引发事务 rollback 与 generic error 的风险。', '在 GitHub 写出短而准确的 QA update。'],
    challenges: ['主流路径成功并不能证明所有安装升级安全。', '语言包由外部目录覆盖时，测试环境与真实机构配置可能不同。', '需要报告风险，但不能把尚未证实的 architecture 问题说成已发生生产故障。'],
    communication: ['Philip 建议该 QA，并指导使用 preview image、EN/FR 环境和 Maildev。', '我向 Philip 报告默认 French flow 成功，同时说明 dataverse.lang.directory 仍需判断。', '结论暂时 hold，而不是为了快速完成直接 Approve。', '风险记录完成后，维护者继续处理 PR；我没有声称解决语言包架构。'],
    rework: ['翻译加入后重新跑完整 French completion email。', '从 UI 成功检查扩展到 installation configuration 路径检查。', '重新表述结论：功能在默认环境工作，但升级配置存在已定位的 residual risk。'],
    decision: '默认 EN/FR 路径可以判定 QA 通过，但把 dataverse.lang.directory 明确记录为 residual risk；不把一次通过扩大成所有安装配置都安全。',
    limitation: '外部 language pack 缺少新 key 的升级风险没有在该 PR 中解决，本次结论只覆盖默认 bundle path。',
    learning: '可靠的 QA 结论必须同时写清“证明了什么”和“没有证明什么”；通过主路径不等于消除配置差异。',
    finalResult: 'French completion email 验证成功，配置风险被明确记录，PR #12544 后来合并。本人完成 QA，不宣称修复外部 language-pack architecture。',
  },
  'roles-11919': {
    success: 'success',
    successLabel: 'Review 目标成功；父 PR 仍开放',
    background: 'PR #11919 新增“用户可分配 roles”API。API 返回的列表必须与真正执行 assignment 的 AssignRoleCommand 完全一致，否则 UI 会显示不能分配的角色，或漏掉本可分配的角色。',
    impact: 'UI 可能展示调用者实际上不能分配的 role，或漏掉本应可分配的 role；授权计算分叉也会形成安全与支持成本。',
    process: ['把新增 availableRoles 计算与 production command authorization 对齐比较。', '检查 role.permissions 与 Manage*Permissions 的组合。', '检查 endpoint 传 User 还是完整 DataverseRequest。', '检查 integration tests 是否真的执行一个返回的 role assignment。', '基于两处授权 mismatch 提交 Changes Requested。'],
    myWork: ['发现缺少 Manage*Permissions 条件。', '发现 User 参数会丢失 IP、mail-domain 等 request-dependent groups。', '发现两处 cleanup response assertion typo。', '用 command、service 和 tests 三条证据链解释风险。'],
    challenges: ['新增测试通过不代表 authorization contract 正确。', '权限计算散落在 API、service 和 command 层，需要对比真实 enforcement path。', '作为 reviewer 必须明确边界：发现问题而不是接管原作者实现。'],
    communication: ['Philip 直接询问、指派并要求 review。', '我在 PR 中给出两个具体 mismatch、对应代码位置和建议 integration test。', '沟通结果采用 Changes Requested，而不是模糊的普通 comment。', '后续修改责任仍归原作者；没有记录到需要我重写父 PR 的 Philip 指示。'],
    rework: ['本项没有第二轮本人实现，因为任务角色是独立 review。', '在下结论前重新核对 AssignRoleCommand 和 request-dependent permissions，确保 finding 不是风格意见。'],
    decision: '基于两处 authorization contract mismatch 提交 Changes Requested，而不是普通评论；维持 reviewer 边界，不接管父 PR 的实现。',
    limitation: '父 PR #11919 仍开放，原作者尚未完成和验证 remediation，因此结果只能是 review complete。',
    learning: '负责展示“可执行选项”的 API 必须复用真正执行操作时的 authorization context；相似计算不是相同 contract。',
    finalResult: '本人授权 review 已完整提交并达到目标。父 PR #11919 仍开放，不能说 API 是本人实现或已整体完成。',
  },
  'featured-12381': {
    success: 'success',
    successLabel: 'API QA 成功并正式批准；PR 已合并',
    background: '未发布 collection 的 creator 无法读取自己添加的 featured-item image。修复必须允许真正 creator 访问，同时继续阻止无关 authenticated user。',
    impact: '真正的 collection creator 无法读取自己配置的 featured image；若修复边界过宽，又可能让无关登录用户访问未发布资源。',
    process: ['用 Maven Docker profile 建立本地 Dataverse。', '创建未发布 collection 和带 image 的 featured item。', '分别使用 creator 与 unrelated authenticated user token 请求同一图片。', '运行目标 integration test。', '基于实际 permission boundary 给出 merge 建议。'],
    myWork: ['完成本地 Docker 环境构建。', '构造两个身份和真实 API 数据。', '记录 creator HTTP 200、unrelated user HTTP 204。', '运行 DataversesIT#testListFeaturedItems。', '在 GitHub 提交正式 Approval。'],
    challenges: ['不能只相信作者新增的 integration assertion。', '需要验证允许路径和拒绝路径两侧，避免无意扩大攻击面。', 'SPA UI 被明确排除，本轮必须控制 API QA scope。'],
    communication: ['Philip 直接分配并在 GitHub 指派。', 'Philip 指导本轮先聚焦 API path，并说明 SPA frontend 不在 scope。', '我按该边界执行并用简短结果向 Philip 汇报。', '结论明确写成“from an API QA perspective, ready to merge”。'],
    rework: ['按照 Philip 的范围建议，从可能的端到端 UI 测试收敛为可证明的 API permission contract。', '在 integration test 之外重新手工构造 creator 和 unrelated user 两个真实请求。'],
    decision: '按 Philip 的范围把本轮限定为 API permission boundary：creator 必须成功，无关 authenticated user 必须继续被拒绝；SPA UI 不纳入本轮。',
    limitation: '结论不覆盖 SPA frontend rendering，只证明 API path 和目标 integration behavior。',
    learning: '权限修复必须同时验证 allow 与 deny 两侧。只证明目标用户成功，无法排除访问边界被意外放宽。',
    finalResult: 'Creator 返回 200、无关用户返回 204、目标 integration test 通过。本人正式 Approve，PR #12381 随后合并。',
  },
  'python-247': {
    success: 'success',
    successLabel: '跨版本修复成功并合并',
    background: 'pyDataverse 在 Python 3.14 因 import 时执行全局 nest_asyncio patch 而触发 AsyncLibraryNotFoundError，影响普通脚本、已有 event loop 和 worker thread。',
    impact: '普通脚本、已有 event loop、notebook 和 worker thread 都可能在 import 或同步入口失败，阻碍用户采用 Python 3.14。',
    process: ['在 CPython 3.14.5 和原锁定依赖上复现。', '识别问题是全局 event-loop mutation，而不是单一 API。', '设计统一的 loop-aware synchronous coroutine runner。', '迁移 API、domain、metrics 和 MCP 同步入口。', '建立 Python 3.10–3.14 matrix 与多执行上下文回归。'],
    myWork: ['删除 import-time patch 与 nest_asyncio dependency。', '实现共享 async runner。', '迁移所有相关调用点。', '添加 no-loop、running-loop、worker-thread 与 live constructor tests。', '完成 live Dataverse 连接验证。'],
    challenges: ['只修一个 constructor 会留下其他同步入口。', '需要兼容已经运行 event loop 的 notebook/应用环境。', '不能为了 3.14 破坏 3.10–3.13。'],
    communication: ['Philip 先引导我测试 pyDataverse，我主动选择 #240。', '复现和修复后，我把 PR 与验证结果公开给 Philip/维护者查看。', '主要 code review 与 merge 由 pyDataverse maintainer JR-1991 完成；没有把 maintainer 工作归给 Philip。'],
    rework: ['从单一异常复现扩展为所有同步 coroutine 入口的 clean cutover。', '增加 worker thread 和 running loop 场景后重新跑完整 Python matrix。'],
    decision: '删除 import-time global patch 和 nest_asyncio dependency，建立一个 loop-aware runner，并一次迁移所有同步 coroutine 入口，而不是只修首个异常 callsite。',
    limitation: '验证覆盖当前支持的 Python 3.10–3.14 和已识别执行上下文；未来 runtime 变化仍需由 matrix 持续捕获。',
    learning: 'library import 不应偷偷修改全局 event loop。把同步/异步边界集中到一个可测试入口，比 callsite patch 更可靠。',
    finalResult: 'PR #247 Approved 并合并。Python 3.10–3.14 matrix、6 个 focused regressions、Build、Ruff 和 Python 3.14 live connection 全部通过。',
  },
  'metadata-249': {
    success: 'success',
    successLabel: '最小通用修复当天合并',
    background: 'nested controlled-vocabulary 字段使用 Annotated 类型，代码却直接调用 issubclass()，导致 ORCID metadata 序列化抛出不透明 TypeError。',
    impact: '包含合法 ORCID 或其他 nested controlled vocabulary 的 metadata 无法序列化，用户只得到不指向字段的不透明 TypeError。',
    process: ['复现 ORCID identifier_scheme。', '沿 metadata serialization 定位到 Annotated[str, AfterValidator(...)]。', '确认 Annotated 不是普通 class。', '在 issubclass 前增加 type guard。', '用另一 nested CV 和 no-scheme control 证明不是 ORCID 特例。'],
    myWork: ['提交最小 isinstance(dtype, type) guard。', '增加 ORCID、contributorType 和无 scheme regression tests。', '验证 controlledVocabulary typeClass 和 raw values 不变。'],
    challenges: ['错误发生在深层序列化，异常信息没有指出字段。', '不能为 ORCID 单独写 branch。', '必须保护已有 metadata 输出 contract。'],
    communication: ['Philip 直接要求先 reproduce #241。', '我完成后向 Philip 说明已经复现、修复并给出 PR，邀请检查。', 'JR-1991 review 后确认方案正确并合并。'],
    rework: ['从 ORCID 单点测试扩展到 contributorType，证明 guard 修复的是类型类别而不是字段。', '加入 no-scheme control 后重新运行 focused tests 和 Ruff。'],
    decision: '把故障归因到 Annotated 不是 class 的类型边界，增加通用 type guard；拒绝为 ORCID 写字段特例或改变 raw metadata contract。',
    limitation: '修复覆盖已知 Annotated controlled-vocabulary serialization，不试图在同一 PR 建立完整 schema validation 系统。',
    learning: '从失败样本抽象到真正的类型类别，才能得到小而通用的修复；最小 diff 仍应有跨字段 control。',
    finalResult: 'PR #249 Approved 并合并；4 个 focused regressions 和 Ruff 通过，stored/API raw values 保持兼容。',
  },
  'edit-1039': {
    success: 'partial',
    successLabel: '实现和验证成功；上游尚未合并',
    background: '用户浏览旧 dataset version 后点击 Edit Metadata，SPA 把旧 version 参数继续传给编辑 factory，可能用 stale metadata 覆盖最新内容。浏览历史版本本身必须保持不变。',
    impact: '编辑旧版本时可能把 stale metadata 覆盖到最新 dataset，属于数据完整性风险；同时历史版本浏览功能又不能被修复误伤。',
    process: ['跟踪 route version 到 EditDatasetMetadataFactory。', '与 JSF 和 Edit Terms 的 latest 行为比较。', '只让 edit fetch 固定使用 :latest。', '添加 repository-call regression，保护旧版本浏览路径。', '按 review 删除噪声文档、补 changelog、同步 develop 并重跑 fork checks。'],
    myWork: ['修改 EditDatasetMetadataFactory。', '添加 latest 与 not-old-version assertions。', '补充 changelog。', '处理 review comments 和 branch synchronization。', '核对 Edit Dataset Metadata E2E 4/4。'],
    challenges: ['修复编辑数据完整性时不能改变历史浏览。', 'fork Chromatic 与 S3 workflow 问题会掩盖目标测试状态。', 'review-only docs 被认为噪声，需要 clean cutover 删除。'],
    communication: ['Cheng 在 Philip 建立的三人 DM 中分配；Philip 提供 JSF/Edit Terms 测试背景。', 'Philip 认为 docs/issues 较 noisy，并要求 changelog；我补 changelog，之后按 Cheng 意见彻底删除 docs。', 'Philip 两次要求 merge/rebase develop 以取得 fork workflow 修复；我完成并报告 Chromatic skipped、目标 checks 通过、剩余失败属于 #1053。'],
    rework: ['删除额外 comments、issue number 和 docs/issues。', '加入 CHANGELOG 条目。', '两次同步 develop，重新触发 fork checks。', '重新确认 Edit Dataset Metadata E2E 4/4。'],
    decision: '只在 Edit Metadata fetch 上强制 :latest，历史浏览继续尊重 URL version；按 review 删除噪声文档、补 changelog 并同步 develop。',
    limitation: 'PR #1039 仍 Open/Blocked；目标实现已批准，但不能宣称 upstream merged，部分 workflow 噪声也不属于该修复。',
    learning: '数据完整性修复常需要不对称 contract：读历史必须保留，写入口必须基于最新状态；测试应分别锁住两侧。',
    finalResult: '目标实现、review 修改和本地/CI 验证完成，Cheng 已 Approve；PR #1039 仍 Open/Blocked，因此只能说 implemented and approved，不能说 merged。',
  },
  'scroll-1050': {
    success: 'partial',
    successLabel: '最小修复成功；review 修改尚未完成',
    background: 'Collection Page 多次 infinite-scroll load 后，页面级 scroll range 会延伸到 footer 以下，出现大块空白。要求不能重写 scrolling architecture。',
    impact: '用户多次加载 collection items 后会滚动到 footer 以下的大块空白，破坏页面边界、导航预期和对结果是否结束的判断。',
    process: ['复现多轮 loading 与 page bounds。', '同时检查 sticky header、Sort、footer 和 empty/small/large states。', '通过实际 runtime 实验确认 .items-list 需要本地 positioning context。', 'production CSS 只加入一行 position: relative。', '添加 repeated loading 与 search/sort/filter reset coverage。'],
    myWork: ['完成问题复现和最小 CSS 修复。', '写 116 行 component regression coverage。', '运行 94 个相关 tests、targeted Cypress、typecheck、lint 和 production build。', '控制 PR root-cause wording，不宣称未证明的浏览器内部机制。'],
    challenges: ['很容易用大型 layout refactor 掩盖问题。', '像素尺寸 assertion 在不同环境存在 1px rounding 差异。', '需要保护多个 state reset 行为，不能只检查空白消失。'],
    communication: ['Cheng 在 Philip 建立的三人 DM 中提供该问题；主要 technical review 也来自 Cheng。', '在提交前，我先把最终 PR title/body 给用户确认，并按要求软化 root-cause wording。', '现有记录没有 Philip 对该修复的直接技术反馈，因此不虚构沟通。'],
    rework: ['Cheng 要求两个 strict equality 改成 closeTo(..., 1)，并补 changelog。', '这些 review items 尚未在记录中完成，因此没有把第二轮描述成成功。'],
    decision: '采用一行 position: relative 建立局部 positioning context，拒绝重写 scrolling architecture；用状态型 regression 覆盖 repeated loading 和 reset。',
    limitation: 'PR #1050 仍有 changelog 与 1px tolerance review items 未完成，跨环境像素断言仍需调整。',
    learning: '生产改动小不代表验证也应小。越窄的 CSS fix，越需要用多个 UI state 证明它没有移动其他边界。',
    finalResult: '一行 production fix 和完整本地验证成功；PR #1050 仍 Open/Changes Requested。上游完成状态是 partial。',
  },
  'relations-1048': {
    success: 'partial',
    successLabel: '功能与第一轮 i18n 成功；架构 review 未结束',
    background: 'Modern UI 把 publication relation raw value（例如 IsSupplementedBy）直接显示给用户。需要 human-readable label，但 stored/API/DataCite value 必须保持原样。',
    impact: '用户看到内部 enum 而不是可读 relation label，西班牙语界面也不完整；若直接改 raw value，则会破坏 API、DataCite 和既有 metadata compatibility。',
    process: ['识别 display value 与 submission value 的边界。', '覆盖六种 relation values 和 unknown fallback。', '让 edit dropdown 使用 {value, label}，view 使用相同显示规则。', '第一轮 review 后把 hard-coded English 移入 EN/ES locale resources。', '第二轮 review 要求遵循项目惯例，直接在 component 中翻译。'],
    myWork: ['实现 edit 与 view 两条显示路径。', '保留 raw submission 和已有 dataset compatibility。', '添加 English/Spanish、六个 values、fallback 和 unrelated vocabulary tests。', '处理 helper 命名、文件位置、imports 和 locale review comments。'],
    challenges: ['如果改 raw value 会破坏 metadata compatibility。', '通用 helper 看似整洁，但不符合该 repository 的 component-local translation 惯例。', 'fork E2E 因 S3 secrets 失败，与本 PR 功能无关。'],
    communication: ['Cheng 在 Philip 的三人 DM 中分配并主导 technical review。', 'Philip 在 PR 底部指出 failing checks，并一起追踪 fork workflow/Chromatic 问题。', '我同步 develop，向 Philip 报告 Chromatic 已 skip、label-copy issue 单独跟踪，没有在本 PR 修改 fork workflow。', 'Cheng 第二轮要求移除 helper、直接在 component 翻译；该轮尚未完成。'],
    rework: ['第一轮：删除独立 helper file、移动并重命名函数、修正 import 顺序、加入 EN/ES resources。', '第一轮重新运行 immediate isolated tests 38/38。', '第二轮：direct component translation 的结构调整仍待完成。'],
    decision: '保持 stored/API relation value 不变，只翻译 display label；第一轮抽出 helper，第二轮接受项目惯例，决定改为 component-local translation。',
    limitation: '第二轮架构修改尚未完成，PR #1048 仍 Open/Changes Requested；当前只证明第一轮功能和兼容性。',
    learning: '兼容性工作的核心是分离表示值与提交值；通用 helper 并不自动优于 repository 已形成的本地惯例。',
    finalResult: '六种 labels、两种语言、raw submission 和 80 个相关 tests 已证明第一轮功能；PR #1048 仍 Open/Changes Requested，最终成功状态为 partial。',
  },
  previewers: {
    success: 'paused',
    successLabel: '研究有结果，但原始目标未完成并已暂停',
    background: 'Philip 原始目标是确认本地开发环境里的简单 CSV Previewer，并了解如何构建包含最新 Previewers 的 image。NcML 后来只是 nice-to-have side quest。',
    impact: '团队仍无法确认最初要求的 CSV previewer baseline，且过早扩展到 NcML 消耗了沟通与验证时间，降低 stakeholder 对进展的可见性。',
    process: ['本应先完成 CSV baseline，再决定是否扩大。', '实际过早扩展到三种 NcML provider、NetCDF/HDF5 和 image delivery。', '完成 published NcML 与 draft auxiliary access 实验。', '区分“asset 被打包”和“浏览器已验证”。', '接受反馈后停止扩大，双方同意 pause。'],
    myWork: ['建立可重复的 NcML provider 比较。', '用真实 NetCDF/HDF5 证明 published rendering。', '定位 draft auxiliary request HTTP 403。', '明确标记 CSV visual acceptance 未完成。'],
    challenges: ['技术上解决了更难的问题，但没有先关闭 stakeholder 要的简单问题。', '长篇 AI-assisted 报告降低了沟通效率。', 'draft 与 published authorization 行为不同。'],
    communication: ['Philip 要求 simple CSV baseline，并把 NcML 定义为低优先级 side quest。', '我给出的内容过长、scope 过大；Philip 提醒小块沟通、先完成原始请求、不要继续复杂化。', '我接受反馈，没有为已投入时间辩护，并与 Philip 同意暂停该方向。'],
    rework: ['没有继续追加 CSV 或 draft auth workaround 来制造“完成”。', '重新整理结论：published NcML 成功、draft 403、CSV 未完成、prototype 非 production-ready。', '把工作方式改为先问 expected outcome、Definition of Done、priority、evidence 和 non-goals。'],
    decision: '收到 scope feedback 后停止继续扩展，不用额外 workaround 制造完成感；如实把工作定性为有证据的研究和未完成的 CSV 目标。',
    limitation: '原始 CSV visual acceptance 未完成，draft auxiliary access 仍返回 403，NcML prototype 也不是 production-ready。',
    learning: '先确认 expected outcome、Definition of Done、priority 和 non-goals，再做 side quest；小块证据比长篇技术报告更有助于 stakeholder 决策。',
    finalResult: 'NcML 研究有真实证据，但原始 CSV 目标未完成。9 月 4 日双方同意暂停；这是 scope-control 学习案例，不是成功交付案例。',
  },
  'search-1062': {
    success: 'not-started',
    successLabel: '已接受，尚未开始',
    background: '活跃 depositor 反馈：搜索 Figure1 时无法找到同名 folder/directory。问题可能位于 frontend query、API capability 或 index。',
    impact: '活跃 depositor 无法通过已知 folder 名定位内容，影响数据发现与日常导航；根因尚未确定。',
    process: ['计划先建立可重复 fixture。', '分别检查 folder name 是否进入 frontend query、backend search API 和 Solr index。', '在确认边界后才定义实现 scope。'],
    myWork: ['目前只完成任务接收和优先级记录，没有代码、QA 或 PR。'],
    challenges: ['不能在未复现前假定是 frontend bug。', '现有 open work 尚未收尾，继续增加 WIP 会降低完成率。'],
    communication: ['Philip 建议至少先 reproduce #1062。', '双方尚未形成实施结果、review 或第二轮反馈。'],
    rework: ['没有重做记录，因为尚未进入执行。'],
    decision: '当前只接受“先复现再定 scope”的决策，不预设 frontend、API 或 Solr 中任何一层已经有 bug。',
    limitation: '尚未建立 fixture、完成调查、写代码或验证；Issue #1062 不能计入完成成果。',
    learning: '控制 WIP 本身是工程决策。没有可重复边界之前，不应把猜测包装成实施方案。',
    finalResult: 'Issue #1062 Open；明确标记为 not started，不计入完成成果。',
  },
  'localization-1063': {
    success: 'not-started',
    successLabel: '已接受，尚未开始',
    background: 'Spanish Modern Frontend 中，静态 UI 已翻译，但 file size、date、file type、system tag、facet heading、controlled Subject 和 result counts 仍是英文或未 locale-format。',
    impact: '西班牙语用户在同一结果页看到混合语言和非本地化数字、日期，降低可读性与产品完成度。',
    process: ['计划先把广泛 issue 切成 locale number/date、system labels、facet headings 和 controlled vocabularies。', '明确 user-authored metadata 不应翻译，dataset version 4.0 也不是 decimal。', '逐 slice 建立 acceptance criteria 后再实现。'],
    myWork: ['目前没有实现或 QA delivery，只保留完整 issue 边界和后续拆分思路。'],
    challenges: ['issue 范围很广，若不拆分会重复 #1048 的过度抽象风险。', '翻译系统值与保持用户内容原样之间需要清晰 contract。'],
    communication: ['Philip 先询问 Cheng 是否适合交给我；Cheng 确认可以。', '任务已接受，但还没有开始，因此没有虚构沟通后的重做与成功。'],
    rework: ['无；等待完成更高优先级 open work 后再开始。'],
    decision: '计划先拆成 locale number/date、system labels、facet headings 和 controlled vocabulary 四个 slice，并明确 user-authored content 不翻译。',
    limitation: '任务已接受但尚未开始；故障落在哪一层、每个 slice 的工作量和验证结果都仍未知。',
    learning: '本地化必须先定义“系统生成值”和“用户内容”的边界；广泛 issue 不拆 contract 就容易形成过度抽象。',
    finalResult: 'Issue #1063 Open；状态为 accepted/not started，不计入完成成果。',
  },
  'dataverse-jl-38': {
    success: 'success',
    successLabel: '自主扩展成功并合并',
    background: 'Dataverse.jl tests/examples 依赖 Harvard 生产服务。WAF 返回 HTTP 202 HTML 或空 body 时，library 继续 JSON parse，只显示 UnexpectedEOF，CI 同时受生产可用性影响。',
    impact: 'CI 和文档示例受 Harvard production/WAF 波动控制，失败信息又被 JSON parser 隐藏，导致维护者难以区分网络响应与 library defect。',
    process: ['把 library error handling 与 CI isolation 拆成两个问题。', '先验证 HTTP status、body、content type，再解析 JSON。', '为 REST、download 和 JSON-LD 加 configurable base URL。', '用 gdcc/dataverse-action 启动隔离实例并动态创建 fixture。', '让文档 examples 离线 deterministic。'],
    myWork: ['修改三条 API 路径和错误信息。', '新增 202、empty、non-JSON、malformed JSON unit coverage。', '建立 create、upload、publish、list、download integration flow。', '替换生产 fixtures 与在线 docs 依赖。'],
    challenges: ['需要保留 Harvard 作为 compatibility default。', '隔离测试要动态产生真实数据而不是 mock echo。', '下游特定科学数据仍需单独 fixture 策略，不能夸大本 PR 范围。'],
    communication: ['Philip 分享了 #36，但明确只是觉得有趣，并非正式分配。', '我自主完成 PR；主要 review 由 Dataverse.jl maintainer gaelforget 完成。', 'Philip 没有要求第二轮重做，因此如实标为 self-directed initiative。'],
    rework: ['从只改善错误消息扩展为 CI isolation，但保持两个责任边界清晰。', '根据真实 WAF 行为补全四类错误 tests，并重新跑 Julia 1.9/latest workflows。'],
    decision: '把可诊断错误和 CI isolation 作为两个清晰责任：解析 JSON 前验证响应，同时用 configurable base URL 和隔离 Dataverse 替代生产 fixture。',
    limitation: 'Harvard production 仍保留为 compatibility default；特定科学数据的下游 fixture strategy 不在本 PR 范围。',
    learning: '确定性 CI 是 library reliability 的一部分。外部服务返回成功码也必须先验证 body 与 content type，再进入 parser。',
    finalResult: 'PR #38 merged。CI 不再依赖 Harvard production，Julia 1.9/latest、integration 和 offline docs 通过。',
  },
  'validation-254': {
    success: 'partial',
    successLabel: '设计讨论成功收敛；未实现',
    background: '多个 metadata 问题晚到 traceback 才暴露。最初提议在 pyDataverse 增加 non-throwing、schema-aware pre-flight validation 和 Unicode coverage。',
    impact: 'metadata 问题往往在深层 traceback 才暴露，用户较晚才知道输入无效；但错误的离线 schema 方案还可能给出过期且过度自信的判断。',
    process: ['把多个 issue 归纳为 validation gap。', '提出 structured Finding、draft-only correction 和 no-LLM boundary。', '研究现有 to_pydantic、model_validate、downloadable JSON Schema 和 server two-stage validation。', '接受 maintainer 对已有能力和 schema drift 的纠正。', '删除 cached/offline schema 方案，把 scope 缩到 ValidationError wrapper 与 Unicode round-trip tests。'],
    myWork: ['创建公开 issue #254。', '调查 server schema 的结构约束与 DB-backed controlled vocabulary。', '公开承认 model_validate 已解决 one-pass collection 的原始前提。', '重新定义更小、可维护的 API surface。'],
    challenges: ['原提案对现有 model_validate 和 downloadable schema 了解不足。', 'cached schema 会给出自信但过期的结果。', '结构 validation 与 server-side CV validation 的 ownership 不在同一层。'],
    communication: ['我主动请 Philip review 提案。', 'Philip 连接了 dataverse-pm #26，并询问 downloadable JSON Schema 是否已经满足原需求。', '我按他的提示重新读 source，向 Philip 和 JR-1991 说明原假设错误，并提出拆分/缩小方案。', 'JR-1991 进一步指出 model_validate、live instance 和 dataverse-action；我再次收敛。'],
    rework: ['移除离线 cached-schema 主张。', '不再声称需要新的 validation logic，只建议包装 Pydantic ValidationError。', '保留非拉丁/Unicode round-trip coverage，等待 maintainer 对 result type 的选择。'],
    decision: '接受 Philip 和 maintainer 对前提的纠正，删除 cached/offline schema 主张，把提案缩到 ValidationError wrapper 与 Unicode round-trip coverage。',
    limitation: 'Issue #254 尚未实现；result type 仍待 maintainer 选择，DB-backed controlled vocabulary validation 继续属于 server。',
    learning: '发现前提错误时，公开修正并缩小方案比维护原提案更有价值；validation ownership 必须按真正的数据来源分层。',
    finalResult: '讨论成功把大提案缩成更准确的小范围，但 issue #254 仍 Open，没有实现，不能描述为已交付功能。',
  },
}
